// Code generated by "stringer -type Type"; DO NOT EDIT.

package scan

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[Error-1]
	_ = x[Newline-2]
	_ = x[Assign-3]
	_ = x[Char-4]
	_ = x[Identifier-5]
	_ = x[LeftBrack-6]
	_ = x[LeftParen-7]
	_ = x[Number-8]
	_ = x[Operator-9]
	_ = x[Op-10]
	_ = x[If-11]
	_ = x[Else-12]
	_ = x[Elif-13]
	_ = x[While-14]
	_ = x[End-15]
	_ = x[Ret-16]
	_ = x[RightBrack-17]
	_ = x[RightParen-18]
	_ = x[Semicolon-19]
	_ = x[String-20]
	_ = x[Colon-21]
}

const _Type_name = "EOFErrorNewlineAssignCharIdentifierLeftBrackLeftParenNumberOperatorOpIfElseElifWhileEndRetRightBrackRightParenSemicolonStringColon"

var _Type_index = [...]uint8{0, 3, 8, 15, 21, 25, 35, 44, 53, 59, 67, 69, 71, 75, 79, 84, 87, 90, 100, 110, 119, 125, 130}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
