// Code generated by "go generate robpike.io/ivy/lib"; DO NOT EDIT.

package lib

import _ "embed"

//go:embed lib/_test.ivy
var _test string

//go:embed lib/units.ivy
var units string

var directory = []*Library{
	&Library{
		Name:   "units",
		Doc:    "A library for manipulating physical values while maintaining their units\n(meters, kilograms, and so on). Inspired by John McCarthy's facts.el file and\nthe Unix units(1) command.\n\nValues are shown as a value followed by a quoted list of units,\nsuch as 2.9979245e+08 \"ms⁻¹\". Use the op called val to construct one.\nThe exponents may be written as \"ms⁻¹\" or \"ms-1\".\n\nKnown base units are:\n\tlength (m), mass (kg), charge (C), time (s), kelvin (K), mole (mol).\nSee the list of vars for derived units and interesting constants. For\narithmetic, use mul, div, per, and so on. For multipliers, use unary ops mega,\ncenti and so on.\n\nExamples to try:\n\tcarat\n\tc div mph\n\tatm per gravity mul pound per square inch\n\tcubic mega parsec\n\t(mul/barn yard atmosphere) div joule\n",
		Ops:    "add centi cubic div giga hecto kilo mega micro milli mul nano neg per peta pr square sub tera val",
		Source: units,
		Vars:   "A C G J K N P RH V W acceleration acre alpha alphabet amp angstrom atm atmosphere au avogadro bar barn btu c calorie carat charge constantUnits coulumb current day dyn eV earthgravity earthmass earthradius echarge emass energy erg farad faraday fluidounce foot footpound grain gram gravity h hbar horsepower hour hp inch interval joule jupitergravity jupitermass jupiterradius k kWh kelvin kg knot length lightyear liter m marsgravity marsmass marsradius mass mercurygravity mercurymass mercuryradius meter metricton micron mile minusSigns minute mmhg mole mph neptunegravity neptunemass neptuneradius newton nmass numUnits ohm ounce parsec pascal permeability permittivity plutogravity plutomass plutoradius pmass pound power pressure s saturngravity saturnmass saturnradius sec second slug solarmass solarradiation solarradius superscript temperature tntkiloton ton troypound u uranusgravity uranusmass uranusradius usfluidounce uspound velocity venusgravity venusmass venusradius volt watt yard year 𝛂",
	},
}

var testLibrary = &Library{
	Name:   "_test",
	Doc:    "This\nis\na\ntest.\n",
	Ops:    "add echo",
	Source: _test,
	Vars:   "x y z",
}
