# Copyright 2015 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# Debug printing.

)debug parse
	1

23
	<int (23)>
	23

3 4 rho iota 12
	(<3 4> rho (iota <int (12)>))
	 1  2  3  4
	 5  6  7  8
	 9 10 11 12

op a base b = ((ceil b log a) rho b) encode a
	(((ceil (<var b> log <var a>)) rho <var b>) encode <var a>)
	op a base b = (((ceil (<var b> log <var a>)) rho <var b>) encode <var a>)

)debug parse
	0
