# Copyright 2014 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# Things that should cause failures.
# Comment line beginning "Expect: " is error we expect.

# Expect: undefined global variable "x"
x
	#

# Expect: invalid code points in string
'\x80'
	#

# Expect: cannot index 1 (int)
1[1]
	#

# Expect: cannot index 1/2 (rational)
1/2 [1]
	#

# Expect: cannot index log 2 (float)
(log 2)[1]
	#

# Expect: invalid index (2) (type float) in ((1 2)[1 2 (float 2)])
1 2[1 2 (float 2)]
	#

# Expect: zero denominator in rational
1/0
	#

# Expect: division by zero
1 / 0
	#

# Expect: division by zero
1 / 2 2 rho 0
	#

# Expect: shape mismatch (4) != (2) in assignment (x[1]) = 1 2
x = 3 4 rho iota 12; x[1]=1 2
	#

# Expect: unexpected EOF
op inc b =
 b + 1
 |
	#

# Expect: no definition for unary foo
opdelete foo x
	#

# Expect: no definition for binary foo
opdelete x foo y
	#

# Expect: usage: sys "read" "filename"
sys 'read'
	#

# Expect: sys "abc" not defined
sys 'abc'
	#

# Expect: rot: count must be small integer
0 1 rot iota 6
	#

# Expect: argument name "f" is function name
op f (f x) = x

# Expect: multiple arguments named "x"
op f (x y x) = x

# Expect: multiple arguments named "x"
op x f x = x

# Expect: multiple arguments named "x"
op (x y) f (z x) = x

# Issue 199: no check for reduce first of degenerate matrix. Reduce had the check.
# Expect: shape for matrix is degenerate: (0 3 0)
+/ (0 rho 0) o.== 1 2 3 o.== 0 rho 0

# Expect: shape for matrix is degenerate: (0 3)
+/% (0 rho 0) o.== 1 2 3

# iota argument must be a small integer: (buggy)
iota box 'buggy'

