# Copyright 2019 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# Help.

)help rho
	#
	Unary operators:
		Name              APL   Ivy     Meaning
		Shape             ⍴B    rho     Number of components in each dimension of B

	Binary operators:
		Name                  APL   Ivy     Meaning
		Reshape               A⍴B   rho     Array of shape A with data B

)help about reverse
	#
		Reversal          ⌽B    rot     Reverse elements of B along last axis
		Reversal          ⊖B    flip    Reverse elements of B along first axis
		Monadic transpose ⍉B    transp  Reverse the axes of B

)help o.
	#
	Axis operators:
		Name                APL  Ivy  APL Example  Ivy Example  Meaning (of example)
		Outer product       ∘.   o.   A∘.×B        A o.* B      Outer product of A and B

