# Copyright 2014 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# Assignments, etc.

x = 10
x
	10

x = 10; x
	10

x = iota 10; x[2] = 100; x
	1 100 3 4 5 6 7 8 9 10

# Assignment is an expression.
1 + y = 100
	101

+/iota y = 10
y
	55
	10

3 (x = 77); x
	3 77 77

3 (x=4) rho iota 12; "\n"; x
	 1  2  3  4
	 5  6  7  8
	 9 10 11 12
	 4

'x' (y='y') 'z'
	xyz

(x=7)/2
	7/2

(x = iota 3); x[2] = x[1]; x
	1 1 3

(x = iota 3); x[3] = (x[2] = x[1]); x
	1 1 1

# These odd assigments work in APL (Dyalog at least).
(zz=3) zz
	3 3

yy (yy=3)
	3 3
