# Copyright 2023 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# Tests for sys operations such as time.

# In alphabetical order except for the time ones, which are trickier and
# done last.

sys 'base'
	0 0

)base 16
'%d' text sys 'base'
	16 16

)ibase 16
'%d' text sys 'base'
	16 0

sys 'format'
	""

)format "%g"
sys 'format'
	"%g"

sys 'maxbits'
	1000000000

)maxbits 999
sys 'maxbits'
	999

sys 'maxdigits'
	10000

)maxdigits 999
sys 'maxdigits'
	999

sys 'maxstack'
	100000

)maxstack 999
sys 'maxstack'
	999

)obase 16
'%d' text sys 'base'
	0 16

sys 'origin'
	1

)origin 5
sys 'origin'
	5

sys 'prompt'
	""

)prompt ">>"
sys 'prompt'
	">>"

# Now the time ones. Tricky because of time moving underfoot
# and discrepancies due to the local time zone.

# ivy_test.go sets this to make testing independent of location.
)timezone
	UTC 0

s=sys 'sec'; (s > 1.6e9) s < 3e9
	1 1

rho sys 'time'
	7

2023 1 1 0 0 0 -1e9<= sys 'time'
	1 1 1 1 1 1 1

3000 12 31 24 60 61 1e9 >= sys 'time'
	1 1 1 1 1 1 1

rho 'T' encode sys 'sec'
	7

'T' encode 0
	1970 1 1 0 0 0 0

'T' decode 'T' encode 0
	0

'T' encode 'T' decode 2023 6 15
	2023 6 15 0 0 0 0

# We use (big) floats, so the low bit could round off the wrong way.
1e-9 >= s- 'T' decode 'T' encode s=sys 'sec'
	1

)timezone "EST"
'T' text 0
	Wed Dec 31 19:00:00 EST 1969

# Check that what sys 'date' prints is the same as 'T' text secs.
# But time can shift in the interim, so we look for general agreement.
# They will agree perfectly unless a second ticks mid-expression.
# Unless that second is New Year's, this is fine.
25 <= +/(sys 'date') == ('T' text sys 'sec')
	1

# Convert an interval into days, minutes, seconds. (98 days, 14 hours, 57 minutes and 15 seconds).
0 24 60 60 encode ('T' decode 2023 9 22 3 27 25)-'T' decode 2023 6 15 12 30 10
	98 14 57 15

# Test a very remote time can be built.
'T' text 'T' decode -4713 11 24 12 0 0 0
	Mon Nov 24 12:00:00 UTC -4713

box@ sys 'read' 'testdata/hello.txt'
	(hello world) (Καλημέρα κόσμε) (こんにちは 世界)

box@ sys 'read' 'testdata/no_newline.txt'
	(hello world) (Καλημέρα κόσμε) (こんにちは 世界)

mix ivy@ sys 'read' 'testdata/matrix.txt'
	1 2 3 4
	5 6 7 8

rho sys 'read' 'testdata/empty.txt'
	0
